name: AutomaticInventory
version: ${version}
main: com.neolumia.autoinventory.AutoPlugin

depend: [Material]

description: ${description}

author: Neolumia
website: https://neolumia.com/

commands:
  automaticinventory:
    description: Main command for AutomaticInventory
    usage: /<command>
    aliases: [autoinv]
