name: AutomaticInventory
version: ${version}
main: com.neolumia.autoinventory.AutoPlugin

description: ${description}

author: Neolumia
website: https://neolumia.com/

commands:
  automaticinventory:
    description: Main command for AutomaticInventory
    usage: /<command>
    aliases: [autoinv]

permissions:
  automaticinventory.refill:
    description: If the player is allowed to use AutoRefill
    default: true
  automaticinventory.sort:
    description: If the player is allowed to use AutoSort
    default: true
